const TIPO_OPERACION={
    SUMA:'SUMA',//ya
    RESTA:'RESTA',
    MULTIPLICACION: 'MULTIPLICACION',
    DIVISION: 'DIVISION',
    POTENCIA: 'POTENCIA',
    MODULO:'MODULO',
    UNARIA:'UNARIA',
    NEGACION:'NEGACION',
    IGUALIGUAL:'IGUALIGUAL',//ya
    DIFERENTE:'DIFERENTE',
    MENOR: 'MENOR',
    MENORIGUAL:'MENORIGUAL',
    MAYOR:'MAYOR',
    MAYORIGUAL:'MAYORIGUAL',
    OR:'OR',//ya
    AND:'AND',
    NOT:'NOT'
}
module.exports=TIPO_OPERACION;