const TIPO_INSTRUCCION={
    PRINT:'INST_PRINT',
    DECLARACION: 'INST_DECLARACION',
    ASIGNACION: 'ASIGNACION',
    DEC_METODO:'DEC_METODO',
    MAIN: 'MAIN',
    IF: 'IF',    
    MASMAS: 'MASMAS',
    MENOSMENOS: 'MENOSMENOS',
}
module.exports = TIPO_INSTRUCCION;