const TIPO_INSTRUCCION={
    PRINT:'INST_PRINT',
    DECLARACION: 'INST_DECLARACION',
    ASIGNACION: 'ASIGNACION',
    DEC_METODO:'DEC_METODO',
    MAIN: 'MAIN',
    IF: 'IF',    
    IFCE:"IFCE",
    ELSEIF:"ELSEIF",
    IFCEIF:"IFCEIF",
    FOR: 'FOR',
    WHILE: 'WHILE',
    DOWHILE: 'DOWHILE',
    LIST: 'LIST', 
    MASMAS: 'MASMAS',
    MENOSMENOS: 'MENOSMENOS',
    CASTEO: 'CASTEO',
    SWITCHCASE: 'SWITCHCASE',
    EJE_METODO: 'EJE_METODO'
}
module.exports = TIPO_INSTRUCCION;